### ISSUE TITLE
Empty SVG document is invalid

### ISSUE THREAD

**Issue by RoelN** [fontfont/RoboChrome#8]
An SVG group only gets opened `if pen.d`, but is always closed: https://github.com/fontfont/RoboChrome/blob/master/RoboChrome.roboFontExt/lib/colorfont/__init__.py#L484 (see also line 486)

This results in empty SVG documents that only have one or two `</g>` tags in them, which is invalid SVG.

**Comment by jenskutilek** [comment]
Thanks for reporting, I have fixed it in 051cdcd.
