### ISSUE TITLE
Don't put transform on SVG element

### ISSUE THREAD

**Issue by RoelN** [fontfont/RoboChrome#9]
Doing a `transform` on the SVG element itself fixes the "upside down" Y-axis that SVG has. But this is not valid: https://lists.w3.org/Archives/Public/public-svgopentype/2016Mar/0002.html Firefox turns a blind eye for now, but once they fix this or other applications offer SVG-in-OT support and stick to the spec, the transform won't happen and the letters will be shown upside down.

I fixed this for [ChromaCheck](https://github.com/RoelN/ChromaCheck) by sticking the contents of the SVG in a `<g>` and do the transform on there.

**Comment by jenskutilek** [comment]
Fixed in 95687bf92e4473be6b4bde012e1d1861d03d6b10.
